import {
  Bot,
  Code,
  Database,
  Globe,
  Layers,
  LayoutTemplate,
  Palette,
  Server,
  Smartphone,
  TestTube,
  Wand2,
  LineChart,
  Lightbulb,
  Rocket,
} from "lucide-react"

export const products = [
  {
    id: "1",
    title: "Next.js Boilerplate",
    description: "A production-ready Next.js boilerplate with TypeScript, Tailwind CSS, and authentication built-in.",
    category: "build",
    subcategory: "code-frameworks",
    tags: ["nextjs", "react", "typescript", "free"],
    logo: Code,
    color: "#0070f3",
    featured: true,
    isAd: false,
  },
  {
    id: "2",
    title: "React Admin Dashboard",
    description: "A fully responsive admin dashboard template built with React, Tailwind CSS, and Chart.js.",
    category: "build",
    subcategory: "selling-templates",
    tags: ["react", "javascript", "tailwind", "free"],
    logo: LayoutTemplate,
    color: "#61dafb",
    featured: false,
    isAd: true,
  },
  {
    id: "3",
    title: "Shadcn UI",
    description: "A collection of beautifully designed, accessible, and customizable UI components for React.",
    category: "build",
    subcategory: "design-systems",
    tags: ["react", "typescript", "shadcn", "free"],
    logo: Palette,
    color: "#000000",
    featured: true,
    isAd: false,
  },
  {
    id: "4",
    title: "GPT-4 Chatbot",
    description: "An AI-powered chatbot built with OpenAI's GPT-4 API for natural language processing.",
    category: "innovate",
    subcategory: "ai-tools",
    tags: ["python", "javascript", "react", "openai"],
    logo: Bot,
    color: "#10a37f",
    featured: true,
    isAd: false,
  },
  {
    id: "5",
    title: "Vue.js Design System",
    description: "A comprehensive design system for Vue.js applications with customizable components.",
    category: "build",
    subcategory: "design-systems",
    tags: ["javascript", "vue"],
    logo: Palette,
    color: "#42b883",
    featured: false,
    isAd: true,
  },
  {
    id: "6",
    title: "Express API Starter",
    description: "A minimalist Express.js API starter kit with authentication, validation, and error handling.",
    category: "build",
    subcategory: "code-frameworks",
    tags: ["express", "javascript", "nodejs"],
    logo: Server,
    color: "#000000",
    featured: false,
    isAd: false,
  },
  {
    id: "7",
    title: "Django REST Framework",
    description: "A powerful and flexible toolkit for building Web APIs with Django.",
    category: "build",
    subcategory: "code-frameworks",
    tags: ["django", "python"],
    logo: Server,
    color: "#092e20",
    featured: false,
    isAd: false,
  },
  {
    id: "8",
    title: "Flutter UI Kit",
    description: "A collection of pre-built Flutter widgets and screens for mobile app development.",
    category: "build",
    subcategory: "design-systems",
    tags: ["flutter", "dart"],
    logo: Smartphone,
    color: "#0175C2",
    featured: false,
    isAd: true,
  },
  {
    id: "9",
    title: "Prisma ORM",
    description: "Next-generation ORM for Node.js and TypeScript with type safety and auto-completion.",
    category: "build",
    subcategory: "code-frameworks",
    tags: ["typescript", "nodejs", "free"],
    logo: Database,
    color: "#2D3748",
    featured: false,
    isAd: false,
  },
  {
    id: "10",
    title: "Vercel Deployment",
    description: "Platform for frontend frameworks and static sites with global CDN and serverless functions.",
    category: "grow",
    subcategory: "seo-performance",
    tags: ["nextjs", "react", "free"],
    logo: Globe,
    color: "#000000",
    featured: true,
    isAd: false,
  },
  {
    id: "11",
    title: "Jest Testing Framework",
    description: "JavaScript testing framework with a focus on simplicity and support for large web applications.",
    category: "build",
    subcategory: "code-frameworks",
    tags: ["javascript", "typescript", "react", "free"],
    logo: TestTube,
    color: "#C21325",
    featured: false,
    isAd: false,
  },
  {
    id: "12",
    title: "Webflow",
    description:
      "Visual web design platform that allows users to design, build, and launch responsive websites visually.",
    category: "build",
    subcategory: "no-code-solutions",
    tags: ["webflow", "free"],
    logo: Wand2,
    color: "#4353FF",
    featured: true,
    isAd: true,
  },
  {
    id: "13",
    title: "T3 Stack",
    description: "The best way to start a full-stack, typesafe Next.js app with tRPC, Prisma, and Tailwind CSS.",
    category: "build",
    subcategory: "saas-boilerplates",
    tags: ["nextjs", "react", "typescript", "free"],
    logo: Layers,
    color: "#E8DCFF",
    featured: false,
    isAd: false,
  },
  {
    id: "14",
    title: "SvelteKit Commerce",
    description: "A SvelteKit e-commerce starter template with Stripe integration and content management.",
    category: "grow",
    subcategory: "e-commerce-platforms",
    tags: ["sveltekit", "javascript", "free"],
    logo: LayoutTemplate,
    color: "#FF3E00",
    featured: false,
    isAd: false,
  },
  {
    id: "15",
    title: "Laravel Nova",
    description: "A beautifully designed administration panel for Laravel applications.",
    category: "build",
    subcategory: "code-frameworks",
    tags: ["laravel", "php"],
    logo: Server,
    color: "#FF2D20",
    featured: false,
    isAd: true,
  },
  {
    id: "16",
    title: "React Native Elements",
    description: "Cross-platform React Native UI toolkit that provides ready-to-use components.",
    category: "build",
    subcategory: "design-systems",
    tags: ["react-native", "javascript"],
    logo: Smartphone,
    color: "#61dafb",
    featured: false,
    isAd: false,
  },
  {
    id: "17",
    title: "Astro Blog Template",
    description: "A fast and modern blog template built with Astro and Markdown for content-focused websites.",
    category: "build",
    subcategory: "selling-templates",
    tags: ["astro", "javascript", "free"],
    logo: LayoutTemplate,
    color: "#FF5D01",
    featured: false,
    isAd: false,
  },
  {
    id: "18",
    title: "Remix Indie Stack",
    description: "The Remix Stack for deploying to Fly.io with SQLite, authentication, and more.",
    category: "build",
    subcategory: "saas-boilerplates",
    tags: ["remix", "react", "typescript"],
    logo: Layers,
    color: "#121212",
    featured: false,
    isAd: false,
  },
  {
    id: "19",
    title: "Zapier Automation",
    description: "Connect your apps and automate workflows with easy-to-use integration platform.",
    category: "grow",
    subcategory: "automation-tools",
    tags: ["zapier", "automation"],
    logo: LineChart,
    color: "#FF4A00",
    featured: true,
    isAd: true,
  },
  {
    id: "20",
    title: "Notion Workspace",
    description: "All-in-one workspace for notes, tasks, wikis, and databases.",
    category: "grow",
    subcategory: "collaboration-hubs",
    tags: ["notion", "collaboration"],
    logo: LineChart,
    color: "#000000",
    featured: false,
    isAd: false,
  },
  {
    id: "21",
    title: "Shopify Store",
    description: "E-commerce platform to start, grow, and manage a business with customizable storefronts.",
    category: "grow",
    subcategory: "e-commerce-platforms",
    tags: ["e-commerce", "shopify"],
    logo: LineChart,
    color: "#7AB55C",
    featured: true,
    isAd: false,
  },
  {
    id: "22",
    title: "Google Analytics 4",
    description: "Web analytics service that tracks and reports website traffic with advanced insights.",
    category: "grow",
    subcategory: "marketing-analytics",
    tags: ["google-analytics", "marketing"],
    logo: LineChart,
    color: "#F9AB00",
    featured: false,
    isAd: false,
  },
  {
    id: "23",
    title: "Hugging Face Models",
    description: "Platform for state-of-the-art machine learning models and datasets.",
    category: "innovate",
    subcategory: "ai-tools",
    tags: ["hugging-face", "ai", "python"],
    logo: Lightbulb,
    color: "#FFD21E",
    featured: true,
    isAd: true,
  },
  {
    id: "24",
    title: "Unity Game Engine",
    description: "Cross-platform game engine for creating interactive 2D and 3D content.",
    category: "innovate",
    subcategory: "ar-vr-gaming",
    tags: ["unity", "gaming", "ar-vr"],
    logo: Lightbulb,
    color: "#000000",
    featured: false,
    isAd: false,
  },
  {
    id: "25",
    title: "Tableau Dashboard",
    description: "Interactive data visualization software focused on business intelligence.",
    category: "innovate",
    subcategory: "data-insights",
    tags: ["tableau", "data"],
    logo: Lightbulb,
    color: "#E97627",
    featured: false,
    isAd: false,
  },
  {
    id: "26",
    title: "Raspberry Pi Projects",
    description: "Small single-board computers for DIY electronics projects and IoT applications.",
    category: "innovate",
    subcategory: "iot-robotics",
    tags: ["raspberry-pi", "iot"],
    logo: Lightbulb,
    color: "#C51A4A",
    featured: false,
    isAd: false,
  },
  {
    id: "27",
    title: "Ethereum Development",
    description: "Decentralized, open-source blockchain with smart contract functionality.",
    category: "innovate",
    subcategory: "web3-blockchain",
    tags: ["ethereum", "blockchain", "solidity"],
    logo: Lightbulb,
    color: "#627EEA",
    featured: true,
    isAd: false,
  },
  {
    id: "28",
    title: "Greenly Carbon Tracking",
    description: "Platform to measure, reduce and offset your carbon footprint with actionable insights.",
    category: "future-tech",
    subcategory: "green-tech",
    tags: ["greenly", "sustainability"],
    logo: Rocket,
    color: "#00A389",
    featured: false,
    isAd: false,
  },
  {
    id: "29",
    title: "Neuralink Interface",
    description: "Developing ultra high bandwidth brain-machine interfaces to connect humans and computers.",
    category: "future-tech",
    subcategory: "neurotech-interfaces",
    tags: ["neuralink", "brain-interface"],
    logo: Rocket,
    color: "#007BFF",
    featured: true,
    isAd: true,
  },
  {
    id: "30",
    title: "Qiskit Quantum Framework",
    description: "Open-source SDK for working with quantum computers at the level of pulses, circuits, and algorithms.",
    category: "future-tech",
    subcategory: "quantum-computing",
    tags: ["qiskit", "quantum"],
    logo: Rocket,
    color: "#6929C4",
    featured: false,
    isAd: false,
  },
  {
    id: "31",
    title: "SatelliteKit",
    description: "Tools and APIs for satellite imagery analysis and space-based applications.",
    category: "future-tech",
    subcategory: "space-tech",
    tags: ["satellitekit", "space"],
    logo: Rocket,
    color: "#1E3A8A",
    featured: false,
    isAd: false,
  },
  {
    id: "32",
    title: "RunwayML",
    description: "Machine learning tools for creators to generate and edit content with AI.",
    category: "future-tech",
    subcategory: "synthetic-media",
    tags: ["runwayml", "ai", "media"],
    logo: Rocket,
    color: "#FF2E6D",
    featured: true,
    isAd: false,
  },
]
